#ifndef STARGAZER_IDL_INCLUDED
#define STARGAZER_IDL_INCLUDED

#include <ExtendedDataTypes.idl>

module hagisonic {
  
  struct StarGazerMarkerInfo {
    RTC::Time tm;
    long markerId;
    boolean mapMode;
    RTC::Pose3D pose;
  };

};

#endif